### PR TITLE
Rotation support. Fixes #41

### LINKED ISSUE #41: Rotation doesn't work
When the SVG contains a `polygon` element with `transform="rotate(-x, y)"`, SVG generates errors that `rotate` is an unknown transformation, and it doesn't rotate the element.

Here's a small SVG of a diamond (square rotated 45 degrees) which appears unrotated.

```
<svg width="50" height="50" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <rect id="svg_2" height="25" width="25" y="12.5" x="12.5" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="0" stroke="#000000" fill="#0000ff" transform="rotate(45 25,25) "/>
 </g>
</svg>
```

### PR DESCRIPTION
**Pull request by ashes999**
Please review the untranslate/retranslate code. I hope I got my algebra right (it's been a while ...)

### CODE REVIEW

**Comment by ashes999** [comment]
Code review please? @jcward @gama11

**Comment by jcward** [comment]
Looks good to me.

**Comment by ashes999** [comment]
Please review @ibilon

**Comment by ashes999** [comment]
Looks like I merged this in by mistake. It still needs a review.

**Comment by ibilon** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform `rotate(<a> [<x> <y>])` is equivalent to `translate(<x>, <y>) rotate(<a>) translate(-<x>, -<y>)` but here the translate are in the other order.

Also the `x,y` parameters should be optional, "If optional parameters x and y are not supplied, the rotate is about the origin of the current user coordinate system."

**Comment by ashes999** [comment]
I'll take a look at this next week.

Sorry to get the formula wrong. I reverse-engineered it (didn't think the SVG spec would mention it) from highschool algebra (move to origin, rotate, and move back).

**Pull request merged**
