### PR TITLE
Support for CSS3-style color, rgb() and rgba()

### PR DESCRIPTION
**Pull request by jcward**
An implementation of css-style color support, e.g. rgb(255,0,0), for fill and stroke colors.

- while rgba isn't technically [part of the standard](https://www.w3.org/TR/SVG/types.html#DataTypeColor), it seems to be supported by browsers, gimp, etc
- I didn't (yet) implement the % format, rgb(100%,50%,0)

### CODE REVIEW

**Comment by jcward** [comment]
huh, I appear to have branched this from the 3-char fix. Sorry.

**Comment by ashes999** [comment]
That's okay. But, again, please add a unit test for this.

**Comment by ashes999** [comment]
I'm hesitant to support anything that's not part of the standard. At the very least, it'll make generating the "expected" unit test image complicated.

Do you mind removing that part, and adding test cases for this? Please comment on this PR when you're done.

I merged in the 3-char change, so you're cool as far as branching goes.

**Comment by jcward** [comment]
I'm going to submit a new request with just rgb and the % values. Closing this one.

**Comment by ashes999** [comment]
Thanks, I really appreciate it.

Sorry, this library is very low-traffic, and by virtue of being the last person to touch the code, it's sort of under my ownership now. Albeit I have no idea how most of the code works :)

**Pull request closed without merging**
