### PR TITLE
Roll back PR #41

### PR DESCRIPTION
**Pull request by ashes999**
Remove rotation fix until it can be fixed properly.

Please concur @ibilon, I don't know when I will have time to work on this unfortunately :(

### CODE REVIEW

**Comment by jgranick** [comment]
Can't we leave the PR, and just improve from here? Shouldnt be diifficult to try @ibilon's suggestions

**Comment by ashes999** [comment]
If you like. I'm not writing much Haxe code these days, so I don't know if/when I will get back to this. (Last time, it was about a two year gap.)

It's really your call. I'm okay with leaving a broken implementation of rotation, but it's not the best thing to do.

**Comment by ibilon** [comment]
In both cases rotation won't work as expected, so might as well keep the code and one day improve it.

**Comment by ashes999** [comment]
Okay, I'll close this.

**Pull request closed without merging**
